### ISSUE TITLE
Field Generators are fucking up.

### ISSUE THREAD

**Issue by Spacemanspark** [NTStation/NTstation13#521] opened 2014-05-05 04:38 UTC
Revision: NTS.
Problem Description: Field Generators shut off after two minutes, even with emitters hitting them.
What did you expect to happen? The emitters should remain on, to form the shield around the singularity.
What happened instead? It shuts off, and singularity escapes.
Why is this bad/What are the consequences? Why do you think this is an important issue? The singularity escapes across the damn station. Every damn round.
Steps to reproduce the problem: Turn on the shield generators, and turn on emitters. Watch. They should shut off after a little bit.
Possibly related stuff: N/A.

**Comment by Atskadan** [comment] 2014-05-05 15:19
when i told you to use the issue report format i didnt mean just copy and paste your previous report into the format
just telling us what happens isnt as useful as the details pertaining to it

**Comment by Atskadan** [comment] 2014-06-21 09:33
cannot reproduce

**Comment by RemieRichards** [comment] 2014-06-21 12:00
Cannot reproduce is no reason to close the issue, that's what the Tag is for.

**Comment by Atskadan** [comment] 2014-06-21 12:02
Can we get some more info about it then? I'm beginning to doubt if it's a real issue or if it was already fixed somehow.

**Comment by Spacemanspark** [comment] 2014-07-08 20:20
Close the issue, it was fixed.

**Closed as completed** 2014-07-08 20:34 UTC
Labels: Cannot Reproduce, Bug
